-- AlterTable
ALTER TABLE `AdminBlog`
  ADD COLUMN `content` LONGTEXT NULL,
  ADD COLUMN `featured` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `image` VARCHAR(191) NULL,
  ADD COLUMN `author` VARCHAR(191) NULL,
  ADD COLUMN `authorRole` VARCHAR(191) NULL,
  ADD COLUMN `color` VARCHAR(191) NULL;
